provider: aws
aws:
  account: 
  role: 
  profile: 
  region: us-east-1
bedrock:
  model_id: anthropic.claude-sonnet-4-5-20250929-v1:0
  max_tokens: 4096
  temperature: 0.7
  available_models:
  - id: anthropic.claude-sonnet-4-5-20250929-v1:0
    name: Claude Sonnet 4.5
  - id: amazon.nova-pro-v1:0
    name: Amazon Nova Pro
  - id: amazon.nova-pro-latency-optimized-v1:0
    name: Amazon Nova Pro with latency optimized inference
  - id: amazon.nova-lite-v1:0
    name: Amazon Nova Lite
  - id: amazon.nova-micro-v1:0
    name: Amazon Nova Micro
  - id: anthropic.claude-sonnet-4-20250514-v1:0
    name: Claude Sonnet 4
  - id: anthropic.claude-opus-4-1-20250805-v1:0
    name: Claude Opus 4.1
  - id: anthropic.claude-opus-4-20250514-v1:0
    name: Claude Opus 4
  - id: anthropic.claude-3-7-sonnet-20250219-v1:0
    name: Claude 3.7 Sonnet
  - id: anthropic.claude-3-5-sonnet-20241022-v2:0
    name: Claude 3.5 Sonnet v2
  - id: anthropic.claude-3-5-haiku-20241022-v1:0
    name: Claude 3.5 Haiku
  - id: anthropic.claude-haiku-4-5-20251001-v1:0
    name: Claude Haiku 4.5
  - id: anthropic.claude-3-5-sonnet-20240620-v1:0
    name: Claude 3.5 Sonnet
  - id: anthropic.claude-3-opus-20240229-v1:0
    name: Claude 3 Opus
  - id: anthropic.claude-3-sonnet-20240229-v1:0
    name: Claude 3 Sonnet
  - id: anthropic.claude-3-haiku-20240307-v1:0
    name: Claude 3 Haiku
  - id: anthropic.claude-2-1-v1:0
    name: Claude 2.1
  - id: anthropic.claude-2-0-v1:0
    name: Claude 2.0
  - id: anthropic.claude-instant-v1:0
    name: Claude Instant
  - id: deepseek.r1-v1:0
    name: DeepSeek R1
  - id: openai.gpt-oss-20b-1:0
    name: GPT-OSS 20B - Optimized for low latency and local/specialized use cases
  - id: openai.gpt-oss-120b-1:0
    name: GPT-OSS 120B - Production-ready, general-purpose, high-reasoning model
  - id: meta.llama3-3-70b-instruct-v1:0
    name: Llama 3.3 Instruct (70B)
  - id: meta.llama3-2-90b-instruct-v1:0
    name: Llama 3.2 Instruct (90B)
  - id: meta.llama3-2-11b-instruct-v1:0
    name: Llama 3.2 Instruct (11B)
  - id: meta.llama3-2-3b-instruct-v1:0
    name: Llama 3.2 Instruct (3B)
  - id: meta.llama3-2-1b-instruct-v1:0
    name: Llama 3.2 Instruct (1B)
  - id: meta.llama3-1-405b-instruct-v1:0
    name: Llama 3.1 Instruct (405B)
  - id: meta.llama3-1-70b-instruct-v1:0
    name: Llama 3.1 Instruct (70B)
  - id: meta.llama3-1-70b-instruct-latency-optimized-v1:0
    name: Llama 3.1 Instruct (70B) (w/ latency optimized inference)
  - id: meta.llama3-1-8b-instruct-v1:0
    name: Llama 3.1 Instruct (8B)
  - id: meta.llama3-70b-instruct-v1:0
    name: Llama 3 Instruct (70B)
  - id: meta.llama3-8b-instruct-v1:0
    name: Llama 3 Instruct (8B)
  - id: amazon.titan-text-lite-v1:0
    name: Amazon Titan Text Lite
  - id: amazon.titan-text-express-v1:0
    name: Amazon Titan Text Express
  - id: amazon.titan-text-embeddings-v1:0
    name: Amazon Titan Text Embeddings
  - id: amazon.titan-text-embeddings-v2:0
    name: Amazon Titan Text Embeddings V2
openai:
  api_token: ''
  base_url: https://api.openai.com/v1
  model: gpt-3.5-turbo
  max_tokens: 4096
  temperature: 0.7
  available_models:
  - id: gpt-5-chat-latest
    name: GPT-5 Chat Latest - Optimized for conversational AI and non-reasoning tasks
  - id: gpt-5-2025-08-07
    name: GPT-5 - The best model for coding and agentic tasks across domains
  - id: gpt-5-mini-2025-08-07
    name: GPT-5 Mini - A faster, more cost-efficient version of GPT-5
  - id: gpt-5-nano-2025-08-07
    name: GPT-5 Nano - Fastest, most cost-efficient version of GPT-5
  - id: gpt-5-codex
    name: GPT-5-Codex - Optimized for agentic coding in Codex
  - id: gpt-4.1
    name: GPT-4.1
  - id: gpt-4.1-mini
    name: GPT-4.1 Mini
  - id: gpt-4.1-nano
    name: GPT-4.1 Nano
  - id: o3
    name: O3
  - id: o3-high
    name: O3 (High Reasoning)
  - id: o3-low
    name: O3 (Low Reasoning)
  - id: o4-mini
    name: O4 Mini
  - id: o4-mini-high
    name: O4 Mini (High Reasoning)
  - id: o4-mini-low
    name: O4 Mini (Low Reasoning)
  - id: o3-mini
    name: O3 Mini
  - id: o3-mini-high
    name: O3 Mini (High Reasoning)
  - id: o3-mini-low
    name: O3 Mini (Low Reasoning)
  - id: o1
    name: O1
  - id: o1-preview
    name: O1 Preview
  - id: o1-mini
    name: O1 Mini
  - id: gpt-4o
    name: GPT-4o
  - id: gpt-4o-mini
    name: GPT-4o Mini
  - id: codex-mini-latest
    name: Codex Mini - Cloud-based agent powered by o3, optimized for coding tasks
