"""Compatibility shim for NetPal's internal Textual UI package."""

from __future__ import annotations

from .textual_ui.app import (
    ADScanView,
    AssetsView,
    CreateCredentialScreen,
    CreateAssetScreen,
    CreateFindingScreen,
    CredentialsView,
    CreateProjectScreen,
    DeleteCredentialScreen,
    DeleteAssetScreen,
    DeleteProjectScreen,
    EditAssetDescriptionScreen,
    EditProjectScreen,
    EditTestCaseScreen,
    EvidenceView,
    FindingsView,
    HostsView,
    NetPalApp,
    ProjectsView,
    ReconView,
    SettingsView,
    StandardModalScreen,
    TestCasesView,
    ToolsView,
)
from .textual_ui.components import (
    ActionBar,
    BaseNetPalView,
    DenseFormGrid,
    DetailPane,
    LogPanel,
    MetricStrip,
    OperatorDataTable,
    SafeDataTable,
    SectionHeader,
    SectionIntro,
    TextAction,
    _should_ignore_table_click,
)
from .textual_ui.helpers import (
    ALL_VIEWS,
    VIEW_AD_SCAN,
    VIEW_ASSETS,
    VIEW_CREDENTIALS,
    VIEW_EVIDENCE,
    VIEW_FINDINGS,
    VIEW_HOSTS,
    VIEW_LABELS,
    VIEW_PROJECTS,
    VIEW_RECON,
    VIEW_SETTINGS,
    VIEW_TESTCASES,
    VIEW_TOOLS,
    _build_starter_asset_name,
    _busy_button,
    _duplicate_ip_set,
    _get_interfaces_with_valid_ips,
    _get_path_suggestions,
    _get_testcase_manager,
    _host_label,
    _list_projects,
    _load_config,
    _load_findings_for_project,
    _load_project,
    _nmap_progress_stdin,
    _prepare_starter_asset,
    _reset_table,
    _save_config,
    _set_active_project,
    _severity_color,
    _starter_asset_target_prompt,
)
from .textual_ui.theme import APP_CSS


def run_interactive() -> int:
    """Launch the NetPal interactive TUI."""
    from netpal.utils.tool_paths import check_tools

    if not check_tools():
        return 1

    app = NetPalApp()
    app.run()
    return 0


__all__ = [
    "ADScanView",
    "ALL_VIEWS",
    "APP_CSS",
    "ActionBar",
    "AssetsView",
    "BaseNetPalView",
    "CreateCredentialScreen",
    "CreateAssetScreen",
    "CreateFindingScreen",
    "CreateProjectScreen",
    "CredentialsView",
    "DeleteCredentialScreen",
    "DeleteAssetScreen",
    "DeleteProjectScreen",
    "DenseFormGrid",
    "DetailPane",
    "EditAssetDescriptionScreen",
    "EditProjectScreen",
    "EditTestCaseScreen",
    "EvidenceView",
    "FindingsView",
    "HostsView",
    "LogPanel",
    "MetricStrip",
    "NetPalApp",
    "OperatorDataTable",
    "ProjectsView",
    "ReconView",
    "SafeDataTable",
    "SectionHeader",
    "SectionIntro",
    "SettingsView",
    "StandardModalScreen",
    "TestCasesView",
    "TextAction",
    "ToolsView",
    "VIEW_AD_SCAN",
    "VIEW_ASSETS",
    "VIEW_CREDENTIALS",
    "VIEW_EVIDENCE",
    "VIEW_FINDINGS",
    "VIEW_HOSTS",
    "VIEW_LABELS",
    "VIEW_PROJECTS",
    "VIEW_RECON",
    "VIEW_SETTINGS",
    "VIEW_TESTCASES",
    "VIEW_TOOLS",
    "_build_starter_asset_name",
    "_busy_button",
    "_duplicate_ip_set",
    "_get_interfaces_with_valid_ips",
    "_get_path_suggestions",
    "_get_testcase_manager",
    "_host_label",
    "_list_projects",
    "_load_config",
    "_load_findings_for_project",
    "_load_project",
    "_nmap_progress_stdin",
    "_prepare_starter_asset",
    "_reset_table",
    "_save_config",
    "_set_active_project",
    "_severity_color",
    "_should_ignore_table_click",
    "_starter_asset_target_prompt",
    "run_interactive",
]


if __name__ == "__main__":
    raise SystemExit(run_interactive())
